databases:
  - name: postgres
    ipAllowList: []
    databaseName: my_blog
    user: my_blog_user
services:
  - type: web
    name: MyBlog
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
