databases:
  - name: MyBlog
    databaseName: MyBlog
    user: MyBlog

services:
  - type: web
    name: MyBlog
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: MyBlog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
